# SD212: Graph mining

# Sparse matrices

The objective of this lab is to learn to work with sparse matrices.

In [1]:
import numpy as np
from scipy import sparse

## CSR format

We first focus on the [CSR](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html)  (Compressed Sparse Row) format. Note that there is the [CSC](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html) (Compressed Sparse Column) format, which is nothing but the CSR format of the transpose matrix.

In [2]:
# random matrix (dense format)
X_dense = np.random.randint(3, size = (10,5))

In [3]:
X_dense

array([[2, 2, 2, 0, 2],
       [2, 1, 2, 1, 2],
       [0, 1, 1, 0, 2],
       [2, 1, 2, 0, 2],
       [2, 0, 1, 0, 1],
       [1, 0, 2, 2, 0],
       [2, 0, 1, 1, 0],
       [1, 0, 0, 1, 2],
       [0, 2, 1, 0, 2],
       [0, 0, 1, 2, 0]])

In [4]:
X_csr = sparse.csr_matrix(X_dense)

In [5]:
X_csr.shape

(10, 5)

In [6]:
X_csr.nnz

33

The data structure consists of 3 vectors:

In [7]:
X_csr.indices

array([0, 1, 2, 4, 0, 1, 2, 3, 4, 1, 2, 4, 0, 1, 2, 4, 0, 2, 4, 0, 2, 3,
       0, 2, 3, 0, 3, 4, 1, 2, 4, 2, 3])

In [8]:
X_csr.indptr

array([ 0,  4,  9, 12, 16, 19, 22, 25, 28, 31, 33])

In [9]:
X_csr.data

array([2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2])

## To do

Can you find the number of non-zeros ``nnz`` and the shape of the matrix from these vectors?

In [10]:
nnz = X_csr.indptr[-1]
nnz2 = len(X_csr.data)

shape = (len(X_csr.indptr) -1, max(X_csr.indices) + 1)

print("nnz = ", nnz)
print("nnz2 = ", nnz2)
print("shape = ", shape, "\n")

nnz =  33
nnz2 =  33
shape =  (10, 5) 



## Arithmetic

Usual arithmetic operations apply to sparse matrices. The only contraint is to have the sparse matrix on the left-hand side of the operator.

In [11]:
n_row, n_col = 10, 4
X_dense = np.random.randint(2, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [12]:
X_dense

array([[1, 1, 1, 0],
       [1, 0, 1, 0],
       [1, 1, 1, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 1, 1],
       [0, 0, 0, 0],
       [1, 1, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [13]:
a = np.ones(n_col, dtype=int)

In [14]:
b = X.dot(a)

In [15]:
b  # row sum

array([3, 2, 4, 1, 2, 2, 0, 3, 2, 2], dtype=int32)

In [16]:
a = np.ones(n_row, dtype=int)
b = X.T.dot(a)

In [17]:
b # col sum

array([6, 5, 6, 4], dtype=int32)

In [18]:
A = np.random.randint(2, size=(n_col, 2))
B = X.dot(A)

In [19]:
A

array([[0, 1],
       [1, 1],
       [0, 1],
       [1, 1]])

In [20]:
B

array([[1, 3],
       [0, 2],
       [2, 4],
       [0, 1],
       [2, 2],
       [1, 2],
       [0, 0],
       [1, 3],
       [2, 2],
       [0, 2]], dtype=int32)

In [21]:
A = sparse.csr_matrix(A)
B = X.dot(A)

In [22]:
B

<10x2 sparse matrix of type '<class 'numpy.intc'>'
	with 15 stored elements in Compressed Sparse Row format>

In [23]:
B.toarray()

array([[1, 3],
       [0, 2],
       [2, 4],
       [0, 1],
       [2, 2],
       [1, 2],
       [0, 0],
       [1, 3],
       [2, 2],
       [0, 2]], dtype=int32)

In [24]:
X.T.dot(X)

<4x4 sparse matrix of type '<class 'numpy.intc'>'
	with 16 stored elements in Compressed Sparse Column format>

In [25]:
X.dot(X.T)

<10x10 sparse matrix of type '<class 'numpy.intc'>'
	with 67 stored elements in Compressed Sparse Row format>

In [26]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))
X = sparse.csr_matrix(X_dense)

In [27]:
X

<10x5 sparse matrix of type '<class 'numpy.int32'>'
	with 31 stored elements in Compressed Sparse Row format>

In [28]:
Y = X > 1

In [29]:
Y

<10x5 sparse matrix of type '<class 'numpy.bool_'>'
	with 16 stored elements in Compressed Sparse Row format>

In [30]:
Y.dot(np.ones(n_col, dtype=int))

array([3, 1, 0, 2, 2, 0, 1, 3, 2, 2], dtype=int32)

In [31]:
Y.dot(np.ones(n_col, dtype=bool))

array([ True,  True, False,  True,  True, False,  True,  True,  True,
        True])

In [32]:
Z = 2 * X + 5 * Y

In [33]:
Z

<10x5 sparse matrix of type '<class 'numpy.intc'>'
	with 31 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [34]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Compute the vector of the Euclidean norm of each row.

In [35]:
# Computing the vector of the Euclidean norm of each row
prod = X.dot(X.T)
diag = prod.diagonal()
norm = np.sqrt(diag)

norm

array([1.41421356, 3.46410162, 2.23606798, 2.44948974, 1.73205081,
       3.46410162, 2.23606798, 2.23606798, 3.60555128, 1.        ,
       1.41421356, 2.44948974, 2.23606798, 1.73205081, 1.73205081,
       1.41421356, 2.        , 3.60555128, 2.82842712, 3.        ])

## Slicing

Sparse matrices can be sliced like numpy arrays.

In [36]:
n_row, n_col = 10, 5
X_dense = np.random.randint(3, size = (n_row, n_col))

In [37]:
X_dense

array([[2, 0, 2, 2, 2],
       [0, 1, 1, 1, 0],
       [0, 0, 1, 2, 0],
       [1, 1, 2, 1, 2],
       [0, 1, 0, 1, 0],
       [0, 1, 2, 0, 2],
       [2, 1, 0, 1, 2],
       [0, 0, 0, 0, 1],
       [1, 0, 2, 0, 0],
       [1, 1, 1, 1, 2]])

In [38]:
X = sparse.csr_matrix(X_dense)

print(X)

  (0, 0)	2
  (0, 2)	2
  (0, 3)	2
  (0, 4)	2
  (1, 1)	1
  (1, 2)	1
  (1, 3)	1
  (2, 2)	1
  (2, 3)	2
  (3, 0)	1
  (3, 1)	1
  (3, 2)	2
  (3, 3)	1
  (3, 4)	2
  (4, 1)	1
  (4, 3)	1
  (5, 1)	1
  (5, 2)	2
  (5, 4)	2
  (6, 0)	2
  (6, 1)	1
  (6, 3)	1
  (6, 4)	2
  (7, 4)	1
  (8, 0)	1
  (8, 2)	2
  (9, 0)	1
  (9, 1)	1
  (9, 2)	1
  (9, 3)	1
  (9, 4)	2


In [39]:
indices = [2, 5, 6]

In [40]:
print(X[indices])

  (0, 2)	1
  (0, 3)	2
  (1, 1)	1
  (1, 2)	2
  (1, 4)	2
  (2, 0)	2
  (2, 1)	1
  (2, 3)	1
  (2, 4)	2


In [41]:
print(X[:, [1, 3]])

  (0, 1)	2
  (1, 0)	1
  (1, 1)	1
  (2, 1)	2
  (3, 0)	1
  (3, 1)	1
  (4, 0)	1
  (4, 1)	1
  (5, 0)	1
  (6, 0)	1
  (6, 1)	1
  (9, 0)	1
  (9, 1)	1


## To do 

Consider the following matrix:

In [42]:
n_row, n_col = 20, 10
X = sparse.csr_matrix(np.random.randint(3, size = (n_row, n_col)))

* Select the 5 rows of largest sums and build the corresponding CSR matrix (size 5 x 10).

In [43]:
sum = X.dot(np.ones(n_col))
print(sum)

# take the 5 largest sums
indices = np.argsort(sum)[-5:]
print(indices)

Y = X[indices]
Y

[11.  4.  5. 12. 11.  8.  6.  8. 10.  5. 11.  7. 12. 12. 10.  8.  7. 10.
  9. 11.]
[ 4 19 12  3 13]


<5x10 sparse matrix of type '<class 'numpy.int32'>'
	with 37 stored elements in Compressed Sparse Row format>

## DIAG format

In [44]:
D = sparse.diags(np.arange(10))

In [45]:
D

<10x10 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements (1 diagonals) in DIAgonal format>

In [46]:
D.data

array([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [47]:
D.nnz

10

In [48]:
D = sparse.csr_matrix(D)

In [49]:
D.data

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [50]:
D.nnz

9

In [51]:
n_row, n_col = 10, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

In [52]:
D.dot(X)

<10x4 sparse matrix of type '<class 'numpy.float64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [53]:
D = sparse.diags(np.ones(4))

In [54]:
X.dot(D)

<10x4 sparse matrix of type '<class 'numpy.float64'>'
	with 15 stored elements in Compressed Sparse Row format>

## To do

Consider the following matrix:

In [55]:
n_row, n_col = 20, 4
X = sparse.csr_matrix(np.random.randint(2, size = (n_row, n_col)))

Using sparse diagonal matrices:
* Normalize this matrix so that each row sums to 1 (or to 0 if the whole row is zero). 

In [56]:
# Normalize this matrix so that each row sums to 1 (or to 0 if the whole row is zero).

# convert x data to float
X.data = X.data.astype(float)

sum = X.dot(np.ones(n_col, dtype=float))
print(sum)

for i in range(n_row):
    if sum[i] != 0:
        X.data[X.indptr[i]: X.indptr[i+1]] /= sum[i]

X.data

[2. 4. 1. 3. 3. 3. 1. 3. 2. 1. 3. 1. 3. 1. 3. 3. 2. 1. 2. 2.]


array([0.5       , 0.5       , 0.25      , 0.25      , 0.25      ,
       0.25      , 1.        , 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 1.        , 0.33333333, 0.33333333, 0.33333333,
       0.5       , 0.5       , 1.        , 0.33333333, 0.33333333,
       0.33333333, 1.        , 0.33333333, 0.33333333, 0.33333333,
       1.        , 0.33333333, 0.33333333, 0.33333333, 0.33333333,
       0.33333333, 0.33333333, 0.5       , 0.5       , 1.        ,
       0.5       , 0.5       , 0.5       , 0.5       ])

## COO format

Another way to represent sparse matrices is the COO (COOrdinate) format. It is useful to load a matrix from a list of entries.

In [57]:
row = [1, 4, 2]
col = [2, 0, 2]
data = [1, 2, 3]

In [58]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [59]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in COOrdinate format>

In [60]:
X_coo.row

array([1, 4, 2])

In [61]:
X_coo.col

array([2, 0, 2])

In [62]:
X_coo.data

array([1, 2, 3])

You can change the format:

In [63]:
X_csr = X_coo.tocsr()

In [64]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in Compressed Sparse Row format>

In [65]:
X_csr.indices

array([2, 2, 0])

In [66]:
X_csr.indptr

array([0, 0, 1, 2, 2, 3])

In [67]:
X_csr.data

array([1, 3, 2])

In [68]:
X_csr.tocoo()

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in COOrdinate format>

You can directly load a CSR matrix from COO format:

In [69]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [70]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in Compressed Sparse Row format>

Duplicate entries are summed in CSR, not in COO:

In [71]:
row = [1, 4, 2, 1]
col = [2, 0, 2, 2]
data = [1, 2, 3, 4]

In [72]:
X_coo = sparse.coo_matrix((data, (row, col)), shape=(5, 5))

In [73]:
X_coo

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 4 stored elements in COOrdinate format>

In [74]:
X_coo.data

array([1, 2, 3, 4])

In [75]:
X_csr = sparse.csr_matrix((data, (row, col)), shape=(5, 5))

In [76]:
X_csr

<5x5 sparse matrix of type '<class 'numpy.int32'>'
	with 3 stored elements in Compressed Sparse Row format>

In [77]:
X_csr.data

array([5, 3, 2])

## To do

* Build the following matrix in sparse CSR format:
$$
\begin{pmatrix}
0 & 0 & 1& 2\\
3 & 0& 0& 0\\
0& 0& 4& 0
\end{pmatrix}
$$



* The matrix in sparse CSR format is:
$$
\begin{align}
indptr &= [0,2,3,4] \\
data &= [1,2,3,4] \\
indices &= [2,3,0,2] \\
\end{align}
$$